name: Maybe generate certifi cacert.pem update PR
on:
  schedule:
    # 1:00 AM US-Pacific on Wednesdays
    - cron: '0 8 * * 3'
  workflow_dispatch:
jobs:
  org-check:
    name: Check GitHub Organization
    if: ${{ github.repository_owner == 'pex-tool' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Noop
        run: "true"
  update-cacert-pem:
    name: Maybe generate certifi cacert.pem update PR
    needs: org-check
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Checkout pex/patches/generation-2 branch
        uses: actions/checkout@v4
        with:
          ref: pex/patches/generation-2
      - name: Update certifi cacert.pem
        id: update-certifi
        run: |
          pip install -U pip
          pip install nox
          echo "version=$(nox -e update-certifi-cacert-pem)" >> "$GITHUB_OUTPUT"
      - name: Maybe generate PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: certifi-${{ steps.update-certifi.outputs.version }}/update-cacert.pem
          commit-message: |
            Update to `cacert.pem` from certifi ${{ steps.update-certifi.outputs.version }}.
          title: Update to `cacert.pem` from certifi ${{ steps.update-certifi.outputs.version }}.
          reviewers: jsirois

